Improve Docker build
google/copybara pull request #239
Opened 2023-06-21 14:01 UTC by mering

Fixes #158
Fixes #235

2023-06-21 21:03 UTC, mikelalcon reviewed
I don't know much about docker, but the deletion of this seems that would break existing users:

COPYBARA_CONFIG=copy.bara.sky`
  * allows you to specify a path to a config file, defaults to root `copy.bara.sky`
* `COPYBARA_SUBCOMMAND=migrate`
  * allows you to change the command run, defaults to `migrate`
* `COPYBARA_OPTIONS=''`
  * allows you to specify options for copybara, defaults to none
* `COPYBARA_WORKFLOW=default`
  * allows you to specify the workflow to run, defaults to `default`
* `COPYBARA_SOURCEREF=''`

2023-06-22 10:15 UTC, mering commented
If you want to handle environment arguments, this should definitely done by the executable itself. Adding this as a script to the container, feels like a big hack.

Nevertheless, I added that functionality back to not break existing users for the time being.

2023-09-11 14:55 UTC, mikelalcon requested changes

2023-09-11 15:09 UTC, mering commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
This is suggested as best practice from Docker itself: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get

This is basically what is used in more than 99% of all `Dockerfile`s. Should I still add a comment?

2023-09-11 15:32 UTC, mikelalcon commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
Yes, at least in the commit description. Can you: squash all changes in one and add a commit description that explains all we are doing here?

Thanks!

2023-09-12 09:24 UTC, mering commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
Done

2023-09-12 13:34 UTC, mering commented on Dockerfile
> +# NOTE NullPointerException when using directly ENTRYPOINT["java","-jar","/opt/copybara/copybara_deploy.jar"]
Fixed in #255

2023-09-14 14:23 UTC, closed without merging